#!/usr/bin/env bash

install_nvm(){
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
}

install_nodejs(){
    nvm install $1
}

# install nvm if not installed
if ! [[ -d "$HOME/.nvm/.git" ]]; then
    install_nvm
fi

# install nodejs 
if command -v node &> /dev/null; then
    echo "node is installed"
else
    install_nodejs 22
fi

