#!/usr/bin/env bash

set -euo pipefail


SSH_DIR="$HOME/.ssh"
EMAIL="tiwarivikrant9764@gmail.com"
DOTFILES="$HOME/dotfiles"

# install ansible if not present 
if ! [ -x "$(command -v ansible)" ]; then
    sudo apt install ansible # for linux mint
    # sudo pacman -S ansible --no-confirm  # for arch
fi

# created the ssh keys if not present
if ! [[ -f "$SSH_DIR/id_rsa" ]]; then

    mkdir -p "$SSH_DIR"
    chmod 700 "$SSH_DIR"
    
    ssh-keygen -b 4096 -t rsa -f "$SSH_DIR/id_rsa" -C "$EMAIL"

    cat "$SSH_DIR/id_rsa.pub" >> "$SSH_DIR/authorized_keys"
    chmod 600 "$SSH_DIR/authorized_keys"

fi

cd "$HOME"

# install git if not present
if ! [ -x "$(command -v git)" ]; then
    sudo apt install git # for linux mint
    # sudo pacman -S git --no-confirm # for arch 
fi

# install the dotfiles if not present from my git hub
if ! [[ -d "$DOTFILES" ]]; then
    git clone git@github.com:Kingcrusher9764/dotfiles.git
fi

cd "$DOTFILES"

# run the ansible file
ansible-playbook main.yml --ask-become-pass
