- name: Developer Setup Configuration 
  hosts: localhost
  become: true
  tasks:

  - name: Update the system
    apt:
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian", "Linux Mint"]
    
  - name: Install tmux
    apt:
      name: tmux
      state: latest
      update_cache: true
    when: ansible_distribution in ["Ubuntu", "Debian", "Linux Mint"]

  - name: Install nodejs
    apt:
      name: nodejs
      state: latest
      update_cache: true
    when: ansible_distribution in ["Ubuntu", "Debian", "Linux Mint"]

