- name: Developer Setup Configuration 
  hosts: localhost
  become: true
  tasks:

  - name: Update the system
    apt:
      update_cache: yes
    
  - name: Install tmux
    apt:
      name: tmux
      state: latest
      update_cache: true

  - name: Install nodejs
    apt:
      name: nodejs
      state: latest
      update_cache: true

