- name: Developer Setup Configuration 
  hosts: localhost
  become: true
  tasks:
    
  # - name: Update the system and Install tmux, nodejs and python3 # name of the task
  #   apt:
  #     name: # it is used to list the name of modules
  #       - tmux
  #       - nodejs
  #       - python3
  #     state: latest # it used to check whether the modules are latest or not
  #     update_cache: yes # it is used to update the system
  #   when: ansible_distribution in ["Ubuntu", "Debian", "Linux Mint"] # condition to run the task

  - name: Update the system and Install tmux, nodejs and python3 # name of the task
    package: # it uses the default package manager of the os
      name: # it is used to list the name of modules
        - tmux
        - nodejs
        - python3
      state: latest # it used to check whether the modules are latest or not
      update_cache: yes # it is used to update the system
